#!/usr/bin/with-contenv sh

. /app/cloudflare.sh

# Verify the $API_TOKEN env variables are valid
statusCode=$(verifyToken)

if [ "$statusCode" != "200" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: Invalid CloudFlare Credentials - $statusCode"
  echo "----------------------------------------------------------------"
  echo "Make sure the API_TOKEN variable is correct. You can"
  echo "get your CloudFlare API Token here:"
  echo
  echo "https://dash.cloudflare.com/profile/api-tokens"
  echo "----------------------------------------------------------------"
  exit 1
fi

if [ "$ZONE_ID" == "" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: $ZONE_ID not provided"
  echo "----------------------------------------------------------------"
  echo "Make sure the ZONE variable is correct and the domain exists"
  echo "in your CloudFlare account. You can add a new domain here:"
  echo
  echo "https://www.cloudflare.com/a/add-site"
  echo "----------------------------------------------------------------"
  exit 1
fi

echo "DNS Zone: $ZONE ($ZONE_ID)"

# Check we can get the current public ip address
PublicIpAddress=$(getPublicIpAddress)

if [ "$PublicIpAddress" == "" ]; then
  echo "----------------------------------------------------------------"
  if [ "$RRTYPE" == "AAAA" ]; then
    echo "ERROR: Failed To Get Public IPv6 Address"
    echo "----------------------------------------------------------------"
    echo "You must be running Docker with IPv6 support enabled or this"
    echo "container with host networking enabled."
    echo
    echo "Add '--net=host' to your docker run command or if using"
    echo "docker-compose add 'network_mode: host' to this service."
  else
    echo "ERROR: Failed To Get Public IPv4 Address"
  fi
  echo "----------------------------------------------------------------"
  exit 1
fi

# Get the ID of the dns record from the CloudFlare API
CFDnsRecordName=$(getDnsRecordName)
CFDnsRecordId=$(getDnsRecordId $ZONE_ID $CFDnsRecordName)

# If the dns record does not exist, create it now.
if [ "$CFDnsRecordId" == "null" ]; then
  echo "DNS record for '$CFDnsRecordName' was not found in $ZONE zone. Creating now..."
  CFDnsRecordId=$(createDnsRecord $ZONE_ID $CFDnsRecordName $PublicIpAddress)

  if [ "$CFDnsRecordId" == "null" ]; then
    echo "----------------------------------------------------------------"
    echo "ERROR: Failed to create DNS record '$CFDnsRecordName'"
    echo "----------------------------------------------------------------"
    exit 1
  fi

fi

echo "DNS Record: $CFDnsRecordName ($CFDnsRecordId)"
echo "CF_ZONE_ID=\"$ZONE_ID\" CF_RECORD_ID=\"$CFDnsRecordId\" CF_RECORD_NAME=\"$CFDnsRecordName\"" > /config/cloudflare.conf
echo "*/5	*	*	*	*	/etc/cont-init.d/50-ddns" > /var/spool/cron/crontabs/root
